
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "pimlico-api-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "alpha-orion"
  name        = "pimlico-api-key"
  secret_data = var.pimlico_api_key
  automatic_replication = {
    kms_key_name = "projects/alpha-orion/locations/us-central1/keyRings/flash-loan-keyring/cryptoKeys/flash-loan-key"
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "user-api-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "user-api-service"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_SECRET" = module.db-secret.env_vars.SECRET}, "env_vars" = merge({"alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS, "alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip}, {"redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string, "redis_cache_us_REDIS_HOST" = module.redis-cache-us.host, "redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "db-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "alpha-orion"
  name        = "db-credentials"
  secret_data = var.db_password
  automatic_replication = {
    kms_key_name = "projects/alpha-orion/locations/us-central1/keyRings/flash-loan-keyring/cryptoKeys/flash-loan-key"
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "scanner-service-data-analysis" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "scanner-service-data-analysis"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_SECRET" = module.db-secret.env_vars.SECRET}, "env_vars" = merge({"scanner_output_topic_TOPIC_ID" = module.scanner-output-topic.id}, {"alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip, "alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string, "redis_cache_us_REDIS_HOST" = module.redis-cache-us.host, "redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT}, {"historical_data_warehouse_BIGQUERY_EXTERNAL_TABLES" = module.historical-data-warehouse.env_vars.BIGQUERY_EXTERNAL_TABLES, "historical_data_warehouse_BIGQUERY_MATERIALIZED_VIEWS" = module.historical-data-warehouse.env_vars.BIGQUERY_MATERIALIZED_VIEWS, "historical_data_warehouse_BIGQUERY_ROUTINES" = module.historical-data-warehouse.env_vars.BIGQUERY_ROUTINES, "historical_data_warehouse_BIGQUERY_TABLES" = module.historical-data-warehouse.env_vars.BIGQUERY_TABLES, "historical_data_warehouse_BIGQUERY_VIEWS" = module.historical-data-warehouse.env_vars.BIGQUERY_VIEWS, "historical_data_warehouse_BIGQUERY_DATASET" = module.historical-data-warehouse.env_vars.BIGQUERY_DATASET}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker"], ["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/bigquery.dataEditor"], ["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker", "roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/storage.objectViewer", "roles/bigquery.dataEditor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}, "gcs" = {"bucket" = module.market-data-lake.name}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "orchestrator-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "orchestrator-service"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = merge({"pimlico_api_secret_SECRET" = module.pimlico-api-secret.env_vars.SECRET}, {"db_secret_SECRET" = module.db-secret.env_vars.SECRET}), "env_vars" = merge({"scanner_output_topic_TOPIC_ID" = module.scanner-output-topic.id}, {"execution_request_topic_TOPIC_ID" = module.execution-request-topic.id}, {"alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip, "alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string, "redis_cache_us_REDIS_HOST" = module.redis-cache-us.host, "redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker"], ["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker"], ["roles/secretmanager.secretAccessor"], ["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker", "roles/secretmanager.secretAccessor", "roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "executor-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "executor-service"
  containers                    = [{"env_secret_vars" = {"db_secret_SECRET" = module.db-secret.env_vars.SECRET}, "env_vars" = merge({"execution_request_topic_TOPIC_ID" = module.execution-request-topic.id}, {"alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS, "alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip}, {"redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string, "redis_cache_us_REDIS_HOST" = module.redis-cache-us.host, "redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker"], ["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker", "roles/secretmanager.secretAccessor", "roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"name" = "cloudsql", "cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  max_instance_request_concurrency = "80"
  depends_on                       = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "ai-optimizer-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "ai-optimizer-service"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_SECRET" = module.db-secret.env_vars.SECRET}, "env_vars" = merge({"alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip, "alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string, "redis_cache_us_REDIS_HOST" = module.redis-cache-us.host, "redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/aiplatform.user"], ["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/aiplatform.user", "roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"name" = "cloudsql", "cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}}]
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_apis_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "dashboard-frontend" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "flash-loan-dashboard"
  containers                    = [{"ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_SECRET" = module.db-secret.env_vars.SECRET}, "env_vars" = merge({"alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip, "alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string, "redis_cache_us_REDIS_HOST" = module.redis-cache-us.host, "redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT})}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "withdrawal-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "withdrawal-service"
  containers                    = [{"ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = merge({"withdrawal_wallet_secret_SECRET" = module.withdrawal-wallet-secret.env_vars.SECRET}, {"db_secret_SECRET" = module.db-secret.env_vars.SECRET}), "env_vars" = merge({"alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip, "alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_us_REDIS_HOST" = module.redis-cache-us.host, "redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT, "redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string})}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/secretmanager.secretAccessor", "roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "vertex-ai-apis" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = "alpha-orion"
  activate_apis = ["aiplatform.googleapis.com"]
  depends_on    = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "scanner-output-topic" {
  source             = "github.com/terraform-google-modules/terraform-google-pubsub?ref=v8.3.2"
  project_id         = "alpha-orion"
  topic              = "raw-opportunities"
  push_subscriptions = concat([{"name" = module.scanner-service-data-analysis.apphub_service_uri.service_id, "oidc_service_account_email" = module.scanner-service-data-analysis.service_account_id.email, "push_endpoint" = module.scanner-service-data-analysis.service_uri}], [{"push_endpoint" = module.orchestrator-service.service_uri, "name" = module.orchestrator-service.apphub_service_uri.service_id, "oidc_service_account_email" = module.orchestrator-service.service_account_id.email}])
  pull_subscriptions = concat([{"name" = module.scanner-service-data-analysis.service_name, "service_account" = module.scanner-service-data-analysis.service_account_id.email}], [{"name" = module.orchestrator-service.service_name, "service_account" = module.orchestrator-service.service_account_id.email}])
  depends_on         = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "execution-request-topic" {
  source             = "github.com/terraform-google-modules/terraform-google-pubsub?ref=v8.3.2"
  project_id         = "alpha-orion"
  topic              = "flash-loan-execution-requests"
  push_subscriptions = concat([{"name" = module.orchestrator-service.apphub_service_uri.service_id, "oidc_service_account_email" = module.orchestrator-service.service_account_id.email, "push_endpoint" = module.orchestrator-service.service_uri}], [{"name" = module.executor-service.apphub_service_uri.service_id, "oidc_service_account_email" = module.executor-service.service_account_id.email, "push_endpoint" = module.executor-service.service_uri}])
  pull_subscriptions = concat([{"name" = module.orchestrator-service.service_name, "service_account" = module.orchestrator-service.service_account_id.email}], [{"name" = module.executor-service.service_name, "service_account" = module.executor-service.service_account_id.email}])
  depends_on         = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "withdrawal-wallet-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "alpha-orion"
  name        = "withdrawal-wallet-keys"
  secret_data = var.withdrawal_wallet_keys
  automatic_replication = {
    kms_key_name = "projects/alpha-orion/locations/us-central1/keyRings/flash-loan-keyring/cryptoKeys/flash-loan-key"
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "ai-terminal-frontend" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "ai-terminal-frontend"
  containers                    = [{"container_name" = "service-container", "env_secret_vars" = {"db_secret_SECRET" = module.db-secret.env_vars.SECRET}, "env_vars" = merge({"alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip, "alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT, "redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string, "redis_cache_us_REDIS_HOST" = module.redis-cache-us.host}), "ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "ai-agent-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "ai-agent-service"
  containers                    = [{"env_vars" = merge({"alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip, "alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string, "redis_cache_us_REDIS_HOST" = module.redis-cache-us.host, "redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_SECRET" = module.db-secret.env_vars.SECRET}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/aiplatform.user"], ["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/aiplatform.user", "roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"name" = "cloudsql", "cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}}]
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_apis_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "benchmarking-scraper-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "benchmarking-scraper-service"
  containers                    = [{"container_name" = "service-container", "env_secret_vars" = {"db_secret_SECRET" = module.db-secret.env_vars.SECRET}, "env_vars" = merge({"alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS, "alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip}, {"redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string, "redis_cache_us_REDIS_HOST" = module.redis-cache-us.host, "redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"name" = "cloudsql", "cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "strategy-engine-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "strategy-engine-service"
  containers                    = [{"env_vars" = merge({"alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip, "alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string, "redis_cache_us_REDIS_HOST" = module.redis-cache-us.host, "redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_SECRET" = module.db-secret.env_vars.SECRET}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "flash-loan-lb-global-lb-frontend" {
  source                          = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v13.2.0"
  name                            = "flash-loan-app-frontend"
  project_id                      = "alpha-orion"
  create_address                  = true
  url_map_input                   = module.flash-loan-lb-global-lb-backend.backend_service_info
  ssl                             = true
  managed_ssl_certificate_domains = ["flashloan.example.com"]
  depends_on                      = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "flash-loan-lb-global-lb-backend" {
  source                  = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.2.0"
  name                    = "flash-loan-app-backend"
  project_id              = "alpha-orion"
  load_balancing_scheme   = "EXTERNAL_MANAGED"
  protocol                = "HTTP"
  enable_cdn              = true
  serverless_neg_backends = concat([{"region" = module.dashboard-frontend.location, "service_name" = module.dashboard-frontend.service_name, "service_version" = "", "type" = "cloud-run"}], [{"region" = module.dashboard-frontend-eu.location, "service_name" = module.dashboard-frontend-eu.service_name, "service_version" = "", "type" = "cloud-run"}])
  depends_on              = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "pimlico-api-secret-eu" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "alpha-orion"
  name        = "pimlico-api-key-eu"
  secret_data = var.pimlico_api_key
  automatic_replication = {
    kms_key_name = "projects/alpha-orion/locations/europe-west1/keyRings/flash-loan-keyring-eu/cryptoKeys/flash-loan-key-eu"
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "db-secret-eu" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "alpha-orion"
  name        = "db-credentials-eu"
  secret_data = var.db_password_eu
  automatic_replication = {
    kms_key_name = "projects/alpha-orion/locations/europe-west1/keyRings/flash-loan-keyring-eu/cryptoKeys/flash-loan-key-eu"
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "withdrawal-wallet-secret-eu" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "alpha-orion"
  name        = "withdrawal-wallet-keys-eu"
  secret_data = var.withdrawal_wallet_keys_eu
  automatic_replication = {
    kms_key_name = "projects/alpha-orion/locations/europe-west1/keyRings/flash-loan-keyring-eu/cryptoKeys/flash-loan-key-eu"
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "scanner-output-topic-eu" {
  source             = "github.com/terraform-google-modules/terraform-google-pubsub?ref=v8.3.2"
  project_id         = "alpha-orion"
  topic              = "raw-opportunities-eu"
  push_subscriptions = concat([{"name" = module.scanner-service-data-analysis-eu.apphub_service_uri.service_id, "oidc_service_account_email" = module.scanner-service-data-analysis-eu.service_account_id.email, "push_endpoint" = module.scanner-service-data-analysis-eu.service_uri}], [{"name" = module.orchestrator-service-eu.apphub_service_uri.service_id, "oidc_service_account_email" = module.orchestrator-service-eu.service_account_id.email, "push_endpoint" = module.orchestrator-service-eu.service_uri}])
  pull_subscriptions = concat([{"name" = module.scanner-service-data-analysis-eu.service_name, "service_account" = module.scanner-service-data-analysis-eu.service_account_id.email}], [{"name" = module.orchestrator-service-eu.service_name, "service_account" = module.orchestrator-service-eu.service_account_id.email}])
  depends_on         = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "execution-request-topic-eu" {
  source             = "github.com/terraform-google-modules/terraform-google-pubsub?ref=v8.3.2"
  project_id         = "alpha-orion"
  topic              = "flash-loan-execution-requests-eu"
  push_subscriptions = concat([{"oidc_service_account_email" = module.orchestrator-service-eu.service_account_id.email, "push_endpoint" = module.orchestrator-service-eu.service_uri, "name" = module.orchestrator-service-eu.apphub_service_uri.service_id}], [{"name" = module.executor-service-eu.apphub_service_uri.service_id, "oidc_service_account_email" = module.executor-service-eu.service_account_id.email, "push_endpoint" = module.executor-service-eu.service_uri}])
  pull_subscriptions = concat([{"name" = module.orchestrator-service-eu.service_name, "service_account" = module.orchestrator-service-eu.service_account_id.email}], [{"service_account" = module.executor-service-eu.service_account_id.email, "name" = module.executor-service-eu.service_name}])
  depends_on         = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "user-api-service-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "user-api-service-eu"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_eu_SECRET" = module.db-secret-eu.env_vars.SECRET}, "env_vars" = merge({"alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip, "alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string, "redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "scanner-service-data-analysis-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "scanner-service-data-analysis-eu"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_eu_SECRET" = module.db-secret-eu.env_vars.SECRET}, "env_vars" = merge({"scanner_output_topic_eu_TOPIC_ID" = module.scanner-output-topic-eu.id}, {"alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS, "alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip}, {"redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string, "redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker"], ["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker", "roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/storage.objectViewer", "roles/bigquery.dataEditor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "orchestrator-service-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "orchestrator-service-eu"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = merge({"pimlico_api_secret_eu_SECRET" = module.pimlico-api-secret-eu.env_vars.SECRET}, {"db_secret_eu_SECRET" = module.db-secret-eu.env_vars.SECRET}), "env_vars" = merge({"scanner_output_topic_eu_TOPIC_ID" = module.scanner-output-topic-eu.id}, {"execution_request_topic_eu_TOPIC_ID" = module.execution-request-topic-eu.id}, {"alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip, "alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string, "redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker"], ["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker"], ["roles/secretmanager.secretAccessor"], ["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker", "roles/secretmanager.secretAccessor", "roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "executor-service-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "executor-service-eu"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_eu_SECRET" = module.db-secret-eu.env_vars.SECRET}, "env_vars" = merge({"execution_request_topic_eu_TOPIC_ID" = module.execution-request-topic-eu.id}, {"alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip, "alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string, "redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker"], ["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker", "roles/secretmanager.secretAccessor", "roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  max_instance_request_concurrency = "80"
  depends_on                       = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "ai-optimizer-service-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "ai-optimizer-service-eu"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_eu_SECRET" = module.db-secret-eu.env_vars.SECRET}, "env_vars" = merge({"alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip, "alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT, "redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/aiplatform.user"], ["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/aiplatform.user", "roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"name" = "cloudsql", "cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}}]
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_apis_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "dashboard-frontend-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "flash-loan-dashboard-eu"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_eu_SECRET" = module.db-secret-eu.env_vars.SECRET}, "env_vars" = merge({"alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip, "alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT, "redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "withdrawal-service-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "withdrawal-service-eu"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = merge({"withdrawal_wallet_secret_eu_SECRET" = module.withdrawal-wallet-secret-eu.env_vars.SECRET}, {"db_secret_eu_SECRET" = module.db-secret-eu.env_vars.SECRET}), "env_vars" = merge({"alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip, "alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT, "redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/secretmanager.secretAccessor", "roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "ai-terminal-frontend-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "ai-terminal-frontend-eu"
  containers                    = [{"env_secret_vars" = {"db_secret_eu_SECRET" = module.db-secret-eu.env_vars.SECRET}, "env_vars" = merge({"alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip, "alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT, "redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string}), "ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "ai-agent-service-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "ai-agent-service-eu"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_eu_SECRET" = module.db-secret-eu.env_vars.SECRET}, "env_vars" = merge({"alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip, "alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string, "redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/aiplatform.user"], ["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/aiplatform.user", "roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_apis_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "benchmarking-scraper-service-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "benchmarking-scraper-service-eu"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"db_secret_eu_SECRET" = module.db-secret-eu.env_vars.SECRET}, "env_vars" = merge({"alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip, "alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT, "redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "strategy-engine-service-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "strategy-engine-service-eu"
  containers                    = [{"env_secret_vars" = {"db_secret_eu_SECRET" = module.db-secret-eu.env_vars.SECRET}, "env_vars" = merge({"alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip, "alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string, "redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "flash-loan-lb-global-lb-backend-ai-terminal" {
  source                  = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.2.0"
  name                    = "flash-loan-app-backend-ai-terminal"
  project_id              = "alpha-orion"
  load_balancing_scheme   = "EXTERNAL_MANAGED"
  protocol                = "HTTP"
  enable_cdn              = true
  serverless_neg_backends = concat([{"service_version" = "", "type" = "cloud-run", "region" = module.ai-terminal-frontend.location, "service_name" = module.ai-terminal-frontend.service_name}], [{"type" = "cloud-run", "region" = module.ai-terminal-frontend-eu.location, "service_name" = module.ai-terminal-frontend-eu.service_name, "service_version" = ""}])
  depends_on              = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "alloydb-primary-us" {
  source                      = "github.com/GoogleCloudPlatform/terraform-google-alloy-db?ref=v8.0.1"
  project_id                  = "alpha-orion"
  cluster_id                  = "flash-loan-db-us"
  location                    = "us-central1"
  cluster_encryption_key_name = "projects/alpha-orion/locations/us-central1/keyRings/flash-loan-keyring/cryptoKeys/flash-loan-key"
  primary_instance = {
    instance_id = "flash-loan-db-us-primary-instance"
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "alloydb-secondary-eu" {
  source                      = "github.com/GoogleCloudPlatform/terraform-google-alloy-db?ref=v8.0.1"
  project_id                  = "alpha-orion"
  cluster_id                  = "flash-loan-db-eu"
  cluster_type                = "SECONDARY"
  location                    = "europe-west1"
  cluster_encryption_key_name = "projects/alpha-orion/locations/europe-west1/keyRings/flash-loan-keyring-eu/cryptoKeys/flash-loan-key-eu"
  primary_instance = {
    instance_id = "flash-loan-db-eu-primary-instance"
  }
  primary_cluster_name = "projects/alpha-orion/locations/us-central1/clusters/flash-loan-db-us"
  depends_on           = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "redis-cache-us" {
  source                  = "github.com/terraform-google-modules/terraform-google-memorystore?ref=v15.2.1"
  project_id              = "alpha-orion"
  region                  = "us-central1"
  name                    = "flash-loan-redis-us"
  memory_size_gb          = 16
  redis_version           = "REDIS_7_2"
  connect_mode            = "DIRECT_PEERING"
  read_replicas_mode      = "READ_REPLICAS_ENABLED"
  replica_count           = 1
  auth_enabled            = true
  transit_encryption_mode = "DISABLED"
  customer_managed_key    = "projects/alpha-orion/locations/us-central1/keyRings/flash-loan-keyring/cryptoKeys/flash-loan-key"
  persistence_config = {
    persistence_mode    = "RDB"
    rdb_snapshot_period = "ONE_HOUR"
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "redis-cache-eu" {
  source                  = "github.com/terraform-google-modules/terraform-google-memorystore?ref=v15.2.1"
  project_id              = "alpha-orion"
  region                  = "europe-west1"
  name                    = "flash-loan-redis-eu"
  memory_size_gb          = 16
  redis_version           = "REDIS_7_2"
  connect_mode            = "DIRECT_PEERING"
  read_replicas_mode      = "READ_REPLICAS_ENABLED"
  replica_count           = 1
  auth_enabled            = true
  transit_encryption_mode = "DISABLED"
  customer_managed_key    = "projects/alpha-orion/locations/europe-west1/keyRings/flash-loan-keyring-eu/cryptoKeys/flash-loan-key-eu"
  persistence_config = {
    persistence_mode    = "RDB"
    rdb_snapshot_period = "ONE_HOUR"
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "market-data-lake" {
  source     = "github.com/terraform-google-modules/terraform-google-cloud-storage//modules/simple_bucket?ref=v12.0.0"
  project_id = "alpha-orion"
  location   = var.market-data-lake_location
  name       = "alpha-orion-market-data-lake"
  iam_members = [{
    member = module.scanner-service-data-analysis.service_account_id.member
    role   = "roles/storage.objectAdmin"
  }]
  storage_class = "STANDARD"
  encryption = {
    default_kms_key_name = "projects/alpha-orion/locations/us-central1/keyRings/flash-loan-keyring/cryptoKeys/flash-loan-key"
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "historical-data-warehouse" {
  source         = "github.com/terraform-google-modules/terraform-google-bigquery?ref=v10.2.1"
  dataset_id     = "flash_loan_historical_data"
  project_id     = "alpha-orion"
  encryption_key = "projects/alpha-orion/locations/us-central1/keyRings/flash-loan-keyring/cryptoKeys/flash-loan-key"
  tables         = [{"schema" = "[{\"description\": \"A string type unique identifier\",\"mode\": \"NULLABLE\",\"name\": \"simpleId\",\"type\": \"STRING\"},{\"description\": \"A field to hold integer values\",\"mode\": \"NULLABLE\",\"name\": \"integerField\",\"type\": \"INTEGER\"},{\"description\": \"Data\",\"mode\": \"NULLABLE\",\"name\": \"data\",\"type\": \"STRING\"}]", "table_id" = "table-1"}]
  depends_on     = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "order-management-service-us" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "order-management-service-us"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_vars" = merge({"alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip, "alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT, "redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string, "redis_cache_us_REDIS_HOST" = module.redis-cache-us.host}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "order-management-service-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "order-management-service-eu"
  containers                    = [{"env_vars" = merge({"alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip, "alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string, "redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "risk-management-service-us" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "us-central1"
  service_name                  = "risk-management-service-us"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_vars" = merge({"alloydb_primary_us_ALLOYDB_INSTANCE_HOST" = module.alloydb-primary-us.primary_instance_ip, "alloydb_primary_us_ALLOYDB_READ_REPLICAS" = module.alloydb-primary-us.env_vars.ALLOYDB_READ_REPLICAS}, {"redis_cache_us_REDIS_PORT" = module.redis-cache-us.env_vars.REDIS_PORT, "redis_cache_us_REDIS_AUTH_STRING" = module.redis-cache-us.auth_string, "redis_cache_us_REDIS_HOST" = module.redis-cache-us.host}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-primary-us.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "risk-management-service-eu" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "alpha-orion"
  location                      = "europe-west1"
  service_name                  = "risk-management-service-eu"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_vars" = merge({"alloydb_secondary_eu_ALLOYDB_READ_REPLICAS" = module.alloydb-secondary-eu.env_vars.ALLOYDB_READ_REPLICAS, "alloydb_secondary_eu_ALLOYDB_INSTANCE_HOST" = module.alloydb-secondary-eu.primary_instance_ip}, {"redis_cache_eu_REDIS_AUTH_STRING" = module.redis-cache-eu.auth_string, "redis_cache_eu_REDIS_HOST" = module.redis-cache-eu.host, "redis_cache_eu_REDIS_PORT" = module.redis-cache-eu.env_vars.REDIS_PORT}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/alloydb.admin"], ["roles/redis.editor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/cloudkms.viewer", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.alloydb-secondary-eu.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-alpha-orion, module.project-services-billing-project]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat([module.user-api-service.apphub_service_uri], [module.scanner-service-data-analysis.apphub_service_uri], [module.orchestrator-service.apphub_service_uri], [module.executor-service.apphub_service_uri], [module.ai-optimizer-service.apphub_service_uri], [module.dashboard-frontend.apphub_service_uri], [module.withdrawal-service.apphub_service_uri], [module.ai-terminal-frontend.apphub_service_uri], [module.ai-agent-service.apphub_service_uri], [module.benchmarking-scraper-service.apphub_service_uri], [module.strategy-engine-service.apphub_service_uri], module.flash-loan-lb-global-lb-frontend.apphub_service_uri, module.flash-loan-lb-global-lb-backend.apphub_service_uri, [module.user-api-service-eu.apphub_service_uri], [module.scanner-service-data-analysis-eu.apphub_service_uri], [module.orchestrator-service-eu.apphub_service_uri], [module.executor-service-eu.apphub_service_uri], [module.ai-optimizer-service-eu.apphub_service_uri], [module.dashboard-frontend-eu.apphub_service_uri], [module.withdrawal-service-eu.apphub_service_uri], [module.ai-terminal-frontend-eu.apphub_service_uri], [module.ai-agent-service-eu.apphub_service_uri], [module.benchmarking-scraper-service-eu.apphub_service_uri], [module.strategy-engine-service-eu.apphub_service_uri], module.flash-loan-lb-global-lb-backend-ai-terminal.apphub_service_uri, [module.redis-cache-us.apphub_service_uri], [module.redis-cache-eu.apphub_service_uri], [module.market-data-lake.apphub_service_uri], [module.order-management-service-us.apphub_service_uri], [module.order-management-service-eu.apphub_service_uri], [module.risk-management-service-us.apphub_service_uri], [module.risk-management-service-eu.apphub_service_uri])
  application_id = var.apphub_application_id
}
module "project-services-alpha-orion" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "alpha-orion"
  disable_services_on_destroy = false
  activate_apis               = ["accesscontextmanager.googleapis.com", "admin.googleapis.com", "alloydb.googleapis.com", "appengine.googleapis.com", "bigquery.googleapis.com", "bigquerystorage.googleapis.com", "billingbudgets.googleapis.com", "certificatemanager.googleapis.com", "cloudbilling.googleapis.com", "cloudkms.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "dns.googleapis.com", "essentialcontacts.googleapis.com", "iam.googleapis.com", "iamcredentials.googleapis.com", "iap.googleapis.com", "memcache.googleapis.com", "monitoring.googleapis.com", "oslogin.googleapis.com", "pubsub.googleapis.com", "redis.googleapis.com", "run.googleapis.com", "secretmanager.googleapis.com", "serviceconsumermanagement.googleapis.com", "servicedirectory.googleapis.com", "servicenetworking.googleapis.com", "serviceusage.googleapis.com", "storage-api.googleapis.com", "storage.googleapis.com", "vpcaccess.googleapis.com"]
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "alpha-orion"
  disable_services_on_destroy = false
  activate_apis               = ["accesscontextmanager.googleapis.com", "admin.googleapis.com", "alloydb.googleapis.com", "appengine.googleapis.com", "apphub.googleapis.com", "bigquery.googleapis.com", "bigquerystorage.googleapis.com", "billingbudgets.googleapis.com", "certificatemanager.googleapis.com", "cloudbilling.googleapis.com", "cloudkms.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "dns.googleapis.com", "essentialcontacts.googleapis.com", "iam.googleapis.com", "iamcredentials.googleapis.com", "iap.googleapis.com", "memcache.googleapis.com", "monitoring.googleapis.com", "oslogin.googleapis.com", "pubsub.googleapis.com", "redis.googleapis.com", "run.googleapis.com", "secretmanager.googleapis.com", "serviceconsumermanagement.googleapis.com", "servicedirectory.googleapis.com", "servicenetworking.googleapis.com", "serviceusage.googleapis.com", "storage-api.googleapis.com", "storage.googleapis.com", "vpcaccess.googleapis.com"]
}
