
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "user-api-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.user-api-service.service_uri
}
output "scanner-service-data-analysis_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.scanner-service-data-analysis.service_uri
}
output "orchestrator-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.orchestrator-service.service_uri
}
output "executor-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.executor-service.service_uri
}
output "ai-optimizer-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.ai-optimizer-service.service_uri
}
output "dashboard-frontend_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.dashboard-frontend.service_uri
}
output "withdrawal-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.withdrawal-service.service_uri
}
output "ai-terminal-frontend_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.ai-terminal-frontend.service_uri
}
output "ai-agent-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.ai-agent-service.service_uri
}
output "benchmarking-scraper-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.benchmarking-scraper-service.service_uri
}
output "strategy-engine-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.strategy-engine-service.service_uri
}
output "flash-loan-lb-global-lb-frontend_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.flash-loan-lb-global-lb-frontend.external_ip
}
output "flash-loan-lb-global-lb-frontend_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.flash-loan-lb-global-lb-frontend.external_ipv6_address
}
output "flash-loan-lb-global-lb-frontend_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.flash-loan-lb-global-lb-frontend.ip_address_internal_managed_http
}
output "flash-loan-lb-global-lb-frontend_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.flash-loan-lb-global-lb-frontend.ip_address_internal_managed_https
}
output "user-api-service-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.user-api-service-eu.service_uri
}
output "scanner-service-data-analysis-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.scanner-service-data-analysis-eu.service_uri
}
output "orchestrator-service-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.orchestrator-service-eu.service_uri
}
output "executor-service-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.executor-service-eu.service_uri
}
output "ai-optimizer-service-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.ai-optimizer-service-eu.service_uri
}
output "dashboard-frontend-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.dashboard-frontend-eu.service_uri
}
output "withdrawal-service-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.withdrawal-service-eu.service_uri
}
output "ai-terminal-frontend-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.ai-terminal-frontend-eu.service_uri
}
output "ai-agent-service-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.ai-agent-service-eu.service_uri
}
output "benchmarking-scraper-service-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.benchmarking-scraper-service-eu.service_uri
}
output "strategy-engine-service-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.strategy-engine-service-eu.service_uri
}
output "redis-cache-us_host" {
  description = "The IP address of the instance."
  value       = module.redis-cache-us.host
}
output "redis-cache-us_port" {
  description = "The port number of the exposed Redis endpoint."
  value       = module.redis-cache-us.port
}
output "redis-cache-eu_host" {
  description = "The IP address of the instance."
  value       = module.redis-cache-eu.host
}
output "redis-cache-eu_port" {
  description = "The port number of the exposed Redis endpoint."
  value       = module.redis-cache-eu.port
}
output "order-management-service-us_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.order-management-service-us.service_uri
}
output "order-management-service-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.order-management-service-eu.service_uri
}
output "risk-management-service-us_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.risk-management-service-us.service_uri
}
output "risk-management-service-eu_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.risk-management-service-eu.service_uri
}
