
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "market-data-lake_location" {
  description = "The location of the bucket. See https://cloud.google.com/storage/docs/locations."
  type = string
}
variable "apphub_project_id" {
  description = "The project ID of the host project where AppHub application is created."
  type = string
}
variable "apphub_location" {
  description = "The location of AppHub application."
  type = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type = string
}
variable "image_versions" {
  description = "Map of service names to their image versions"
  type = map(string)
  default = {}
}
variable "artifact_registry_repo" {
  description = "Artifact Registry repository name"
  type = string
  default = "alpha-orion-repo"
}

# Secret variables - DO NOT commit actual values to version control
# These should be provided via environment variables or secure secret management

variable "pimlico_api_key" {
  description = "Pimlico API key for US region"
  type = string
  sensitive = true
}

variable "pimlico_api_key_eu" {
  description = "Pimlico API key for EU region"
  type = string
  sensitive = true
}

variable "db_password" {
  description = "Database password for US region"
  type = string
  sensitive = true
}

variable "db_password_eu" {
  description = "Database password for EU region"
  type = string
  sensitive = true
}

variable "withdrawal_wallet_keys" {
  description = "Withdrawal wallet keys for US region"
  type = string
  sensitive = true
}

variable "withdrawal_wallet_keys_eu" {
  description = "Withdrawal wallet keys for EU region"
  type = string
  sensitive = true
}

variable "alloydb_password" {
  description = "AlloyDB initial user password"
  type = string
  sensitive = true
}
